version: '3'
services:
    discord-doo-bot:
        build: .
        restart: always
        labels:
            com.centurylinklabs.watchtower.enable: false
        volumes:
            - ./_database/data:/app/data
